GazeboXBotPlugin:
  gains:
    RShSag:   {p: 0, d: 0}
    RShLat:   {p: 0, d: 0}
    RShYaw:   {p: 0, d: 0}
    RElbj:    {p: 0, d: 0}
    RWrj1:    {p: 0, d: 0}
    LShSag:   {p: 0, d: 0}
    LShLat:   {p: 0, d: 0}
    LShYaw:   {p: 0, d: 0}
    LElbj:    {p: 0, d: 0}
    LWrj1:    {p: 0, d: 0}
    WaistSag: {p: 0, d: 0}
    WaistYaw: {p: 0, d: 0}
    WaistLat: {p: 0, d: 0}
    LHipYaw:  {p: 0, d: 0}
    RHipYaw:  {p: 0, d: 0}
    RHipLat:  {p: 0, d: 0}
    RHipSag:  {p: 0, d: 0}
    RKneeSag: {p: 0, d: 0}
    RAnkSag:  {p: 0, d: 0}
    RAnkLat:  {p: 0, d: 0}
    LHipLat:  {p: 0, d: 0}
    LHipSag:  {p: 0, d: 0}
    LKneeSag: {p: 0, d: 0}
    LAnkSag:  {p: 0, d: 0}
    LAnkLat:  {p: 0, d: 0}

HALInterface:
  lib_file: "libXBotEcat"
  lib_name: "ETHERCAT"

x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix : 
  # periodic - priority if needed here

ec_board_ctrl:
  eth_iface: rteth0
  sync_cycle_time_ns: 1000000
  sync_cycle_offset_ns: 0
  power_off_boards: true

ec_boards_base:
  use_pipes: false
  
#############################
# HEAD
#############################

#
LpESC_1:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    impedance:  [100.0, 20.0, 2.0, 0.01, 0.8]

#
LpESC_2:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    impedance:  [100.0, 5.0, 2.0, 0.01, 0.8]

#############################
# RIGHT LEG
#############################

# RL_H_R = 41
HpESC_41:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [4800.0, 0.0, 35.0]
    impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]
    

# RL_H_Y = 42
HpESC_42:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 10.0]
    impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_H_P = 43
HpESC_43:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [4200.0, 0.0, 40.0]
    impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_K = 44
HpESC_44:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [3700.0, 0.0, 35.0]
    impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_A_P = 45
HpESC_45:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [2000.0, 0.0, 30.0]
    impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_A_R = 46
HpESC_46:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 10.0]
    impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

#############################
# LEFT LEG
#############################

# LL_H_R = 51
HpESC_51:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [4800.0, 0.0, 35.0]
    impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_H_Y = 52
HpESC_52:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 10.0]
    impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_H_P = 53
HpESC_53:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [4200.0, 0.0, 40.0]
    impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_K = 54
HpESC_54:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [3700.0, 0.0, 35.0]
    impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_A_P = 55
HpESC_55:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [3700.0, 0.0, 30.0]
    impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_A_R = 56
HpESC_56:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 10.0]
    impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]


#############################
# RIGHT ARM
#############################

# RA_SH_1 = 11
HpESC_11:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_SH_2 = 12
HpESC_12:
  control_mode: idle
  sign: 1
  pos_offset: -90
  #pos_offset: -90 NOTE it was not working for the left_arm joint
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_SH_3 = 13
HpESC_13:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_EL_ = 14
HpESC_14:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_WR_1 = 15
LpESC_15:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_WR_2 = 16
LpESC_16:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_WR_3 = 17
LpESC_17:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]
    impedance:  [100.0, 20.0, 2.0, 0.01, 0.8]

# RA_HA = 19
LpESC_19:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

#############################
# LEFT ARM
#############################

# LA_SH_1 = 21
HpESC_21:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_SH_2 = 22
HpESC_22:
  control_mode: idle
  sign: 1
  pos_offset : 90
  #pos_offset: 90 NOTE it was not working for the left_arm joint
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_SH_3 = 23
HpESC_23:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_EL = 24
HpESC_24:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_WR_1 = 25
LpESC_25:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_2 = 26
LpESC_26:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_3 = 27
LpESC_27:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_HA = 29
LpESC_29:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]

#############################
# WAIST
#############################

# WST_Y = 31
HpESC_31:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 10.0]

# WST_P = 32
HpESC_32:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [3000.0, 0.0, 30.0]

# WST_R = 33
HpESC_33:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 10.0]
