# WALKMAN upper body config

XBotInterface:
  urdf_path: "configs/ADVR_shared/bigman/urdf/bigman_upper_body.urdf"
  srdf_path: "configs/ADVR_shared/bigman/srdf/bigman_upper_body.srdf"
  joint_map_path: "configs/ADVR_shared/bigman/joint_map/bigman_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "XBotRT"
  
RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "AdvrCommandMessage"
  jointstate_message_type: "AdvrJointStateMessage"
  ft_topic_names: [] #"/ft_foot_1", "/ft_foot_2", "/ft_foot_3", "/ft_foot_4"]
  imu_topic_names: []#["/imu_1_data", "/imu_2_data"]
  
XBotRTPlugins:
  #plugins: ["ExoskeletonCommunicationPlugin", "TwoPriorityRtIkPlugin"]
  #plugins: ["ExoskeletonCommunicationPlugin", "HomingExample"]
  plugins: ["HomingExample"] #, "OpenSotIkTestPlugin", "PlayJointSpaceDemo"]
  #plugins: ["ExoskeletonCommunicationPlugin"]
  #plugins: ["PlayJointSpaceDemo"] #, "TwoPriorityRtIkPlugin"]
  
ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

AdvrCommandMessage:
  subclass_name: "CommandAdvr"
  path_to_shared_lib: "libAdvrCommandMessage.so"
  subclass_factory_name: "advrcommandmessage_control_message"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/xbotcore/centauro/command"

AdvrJointStateMessage:
  subclass_name: "AdvrJointState"
  path_to_shared_lib: "libAdvrJointStateMessage.so"
  subclass_factory_name: "advrjointstate_jointstate_message"
  joint_state_topic_name: "/xbotcore/centauro/joint_states"
  
RobotInterfaceYARP:
  subclass_name: "RobotInterfaceYARP"
  path_to_shared_lib: "libRobotInterfaceYARP.so"
  subclass_factory_name: "robot_interface_yarp"
  module_prefix: "test_YARP"
  robot_name: "bigman"
  # different config files for module_prefix
  
RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
