# WALKMAN upper body config

XBotInterface:
  urdf_path: "urdf/bigman_upper_body.urdf"
  srdf_path: "srdf/bigman_upper_body.srdf"
  joint_map_path: "joint_map/bigman_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "YARP"
  
ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  joint_state_name: "/centauro/joint_states"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/centauro/position_controller/command"
  ft_topic_names: ["/ft_foot_1", "/ft_foot_2", "/ft_foot_3", "/ft_foot_4"]
  
RobotInterfaceYARP:
  subclass_name: "RobotInterfaceYARP"
  path_to_shared_lib: "libRobotInterfaceYARP.so"
  subclass_factory_name: "robot_interface_yarp"
  module_prefix: "test_YARP"
  robot_name: "bigman"
  # different config files for module_prefix
  
RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
