# WALKMAN 

XBotInterface:
  urdf_path: "configs/ADVR_shared/bigman/urdf/bigman_floating_base.urdf"
  srdf_path: "configs/ADVR_shared/bigman/srdf/bigman.srdf"
  joint_map_path: "configs/ADVR_shared/bigman/joint_map/bigman_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "XBotRT"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "AdvrCommandMessage"
  jointstate_message_type: "AdvrJointStateMessage"
  ft_topic_names: ["/ft_foot_1", "/ft_foot_2", "/ft_foot_3", "/ft_foot_4"]
  imu_topic_names: []#["/imu_1_data", "/imu_2_data"]

RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"

XBotRTPlugins:
  #plugins: ["ExoskeletonCommunicationPlugin", "TwoPriorityRtIkPlugin"]
  #plugins: ["ExoskeletonCommunicationPlugin", "HomingExample"]
  #plugins: ["HomingExample", "IkRosSharedMemoryPublisher", "OpenSotIk"]
  #plugins: ["HomingExample"]
  plugins: ["HomingExample", "chengxu_walking"]
  #plugins: ["chengxu_walking"]
  io_plugins: []
  #plugins: ["ExoskeletonCommunicationPlugin"]
  #plugins: ["PlayJointSpaceDemo"] #, "TwoPriorityRtIkPlugin"]

MasterCommunicationInterface:
  framework_name: "ROS"
  
CustomCmnd:
  subclass_name: "CustomCmndMessage"
  path_to_shared_lib: "libCustomCmndMessage.so"
  subclass_factory_name: "customcmnd_control_message"
  joint_service_name: "/bigman/position_controller/get_joint_names"
  command_topic_name: "/bigman/position_controller/command"

JointState:
  subclass_name: "JointStateMessage"
  path_to_shared_lib: "libJointStateMessage.so"
  subclass_factory_name: "jointstate_jointstate_message"
  joint_state_topic_name: "/bigman/joint_states"

AdvrCommandMessage:
  subclass_name: "CommandAdvr"
  path_to_shared_lib: "libAdvrCommandMessage.so"
  subclass_factory_name: "advrcommandmessage_control_message"
  joint_service_name: "/bigman/position_controller/get_joint_names"
  command_topic_name: "/xbotcore/bigman/command"

AdvrJointStateMessage:
  subclass_name: "AdvrJointState"
  path_to_shared_lib: "libAdvrJointStateMessage.so"
  subclass_factory_name: "advrjointstate_jointstate_message"
  joint_state_topic_name: "/xbotcore/bigman/joint_states"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"

GazeboXBotPlugin:
  gains:
    RShSag:   {p: 1500, d: 10}
    RShLat:   {p: 1500, d: 10}
    RShYaw:   {p: 1500, d: 10}
    RElbj:    {p: 1500, d: 10}
    RWrj1:    {p: 1500, d: 10}
    LShSag:   {p: 1500, d: 10}
    LShLat:   {p: 1500, d: 10}
    LShYaw:   {p: 1500, d: 10}
    LElbj:    {p: 1500, d: 10}
    LWrj1:    {p: 1500, d: 10}
    WaistSag: {p: 10000, d: 160}
    WaistYaw: {p: 10000, d: 140}
    WaistLat: {p: 10000, d: 100}
    LHipYaw:  {p: 2000, d: 10}
    RHipYaw:  {p: 2000, d: 10}
    RHipLat:  {p: 15000, d: 160}
    RHipSag:  {p: 10000, d: 40}
    RKneeSag: {p: 10000, d: 40}
    RAnkSag:  {p: 10000, d: 40}
    RAnkLat:  {p: 8000, d: 40}
    LHipLat:  {p: 15000, d: 160}
    LHipSag:  {p: 10000, d: 40}
    LKneeSag: {p: 10000, d: 40}
    LAnkSag:  {p: 10000, d: 40}
    LAnkLat:  {p: 8000, d: 40}

    # RShSag:   {p: 2000,  d: 17}
    # RShLat:   {p: 1500,  d: 17}
    # RShYaw:   {p: 1500,  d: 11.5}
    # RElbj:    {p: 1500,  d: 11.5}
    # RWrj1:    {p: 745,  d: 4}
    # LShSag:   {p: 2000,  d: 17}
    # LShLat:   {p: 1500,  d: 17}
    # LShYaw:   {p: 1500,  d: 11.5}
    # LElbj:    {p: 1500,  d: 11.5}
    # LWrj1:    {p: 745,  d: 4}
    # WaistSag: {p: 5500, d: 10}
    # WaistYaw: {p: 4000, d: 10}
    # WaistLat: {p: 4000, d: 10}
    # LHipYaw:  {p: 1063,  d: 10}
    # RHipYaw:  {p: 1063,  d: 10}
    # RHipLat:  {p: 6500, d: 15}
    # RHipSag:  {p: 6500, d: 15}
    # RKneeSag: {p: 6500, d: 15}
    # RAnkSag:  {p: 6500, d: 15}
    # RAnkLat:  {p: 6500, d: 15}
    # LHipLat:  {p: 6500, d: 15}
    # LHipSag:  {p: 6500, d: 15}
    # LKneeSag: {p: 6500, d: 15}
    # LAnkSag:  {p: 6500, d: 15}
    # LAnkLat:  {p: 6500, d: 15}

    # RShSag:   {p: 2500, d: 10}
    # RShLat:   {p: 2500, d: 10}
    # RShYaw:   {p: 2500, d: 10}
    # RElbj:    {p: 2500, d: 10}
    # RWrj1:    {p: 2500, d: 10}
    # LShSag:   {p: 2500, d: 10}
    # LShLat:   {p: 2500, d: 10}
    # LShYaw:   {p: 2500, d: 10}
    # LElbj:    {p: 2500, d: 10}
    # LWrj1:    {p: 2500, d: 10}
    # WaistSag: {p: 6500, d: 15}
    # WaistYaw: {p: 6500, d: 15}
    # WaistLat: {p: 6500, d: 15}
    # LHipYaw:  {p: 1000, d: 10}
    # RHipYaw:  {p: 1000, d: 10}
    # RHipLat:  {p: 6000, d: 25}
    # RHipSag:  {p: 6000, d: 25}
    # RKneeSag: {p: 6000, d: 25}
    # RAnkSag:  {p: 6000, d: 25}
    # RAnkLat:  {p: 6000, d: 25}
    # LHipLat:  {p: 6000, d: 25}
    # LHipSag:  {p: 6000, d: 25}
    # LKneeSag: {p: 6000, d: 25}
    # LAnkSag:  {p: 6000, d: 25}
    # LAnkLat:  {p: 6000, d: 25}

x_bot_core:
  urdf_path: /home/lucamuratore/src/robotology-superbuild/configs/ADVR_shared/bigman/urdf/bigman.urdf
  srdf_path: /home/lucamuratore/src/robotology-superbuild/configs/ADVR_shared/bigman/srdf/bigman.srdf
  joint_map_config: /home/lucamuratore/src/robotology-superbuild/configs/ADVR_shared/bigman/joint_map/bigman_ecat_joint_map.yaml
  
x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix : 
  # periodic - priority if needed here

ec_board_ctrl:
  eth_iface: rteth0
  sync_cycle_time_ns: 2000000
  sync_cycle_offset_ns: 0
  power_off_boards: true

ec_boards_base:
  create_pipes: true
  
#############################
# HEAD
#############################

#
LpESC_1:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    impedance:  [100.0, 20.0, 2.0, 0.01, 0.8]

#
LpESC_2:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    impedance:  [100.0, 5.0, 2.0, 0.01, 0.8]

#############################
# RIGHT LEG
#############################

# RL_H_R = 41
HpESC_41:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [6000.0, 0.0, 50.0]
    impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]
    

# RL_H_Y = 42
HpESC_42:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [1200.0, 0.0, 20.0]
    impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_H_P = 43
HpESC_43:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [5000.0, 0.0, 45.0]
    impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_K = 44
HpESC_44:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [4500.0, 0.0, 40.0]
    impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_A_P = 45
HpESC_45:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [4000.0, 0.0, 40.0]
    impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_A_R = 46
HpESC_46:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [1500.0, 0.0, 20.0]
    impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

#############################
# LEFT LEG
#############################

# LL_H_R = 51
HpESC_51:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [6000.0, 0.0, 50.0]
    impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_H_Y = 52
HpESC_52:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [1200.0, 0.0, 20.0]
    impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_H_P = 53
HpESC_53:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [5000.0, 0.0, 45.0]
    impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_K = 54
HpESC_54:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [4500.0, 0.0, 40.0]
    impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_A_P = 55
HpESC_55:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [4000.0, 0.0, 40.0]
    impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_A_R = 56
HpESC_56:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [1500.0, 0.0, 20.0]
    impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

##############################
## RIGHT LEG
##############################

## RL_H_R = 41
#HpESC_41:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [800.0 , 0.0 , 12.0]
    #mix_position: [4800.0, 0.0, 35.0]
    #impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]
    

## RL_H_Y = 42
#HpESC_42:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [180.0 , 0.0 , 3.0]
    #mix_position: [800.0, 0.0, 10.0]
    #impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## RL_H_P = 43
#HpESC_43:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [700.0 , 0.0 , 10.0]
    #mix_position: [4200.0, 0.0, 40.0]
    #impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## RL_K = 44
#HpESC_44:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [500.0 , 0.0 , 1.0]
    #mix_position: [3700.0, 0.0, 35.0]
    #impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## RL_A_P = 45
#HpESC_45:
  #control_mode: mix_pos_3c
  #sign: -1
  #pos_offset: 0
  #pid :
    #position: [500.0 , 0.0 , 2.0]
    #mix_position: [2000.0, 0.0, 30.0]
    #impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## RL_A_R = 46
#HpESC_46:
  #control_mode: mix_pos_3c
  #sign: -1
  #pos_offset: 0
  #pid :
    #position: [80.0 , 0.0 , 4.0]
    #mix_position: [800.0, 0.0, 10.0]
    #impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

##############################
## LEFT LEG
##############################

## LL_H_R = 51
#HpESC_51:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [800.0 , 0.0 , 12.0]
    #mix_position: [4800.0, 0.0, 35.0]
    #impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## LL_H_Y = 52
#HpESC_52:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [180.0 , 0.0 , 3.0]
    #mix_position: [800.0, 0.0, 10.0]
    #impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## LL_H_P = 53
#HpESC_53:
  #control_mode: mix_pos_3c
  #sign: -1
  #pos_offset: 0
  #pid :
    #position: [700.0 , 0.0 , 10.0]
    #mix_position: [4200.0, 0.0, 40.0]
    #impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## LL_K = 54
#HpESC_54:
  #control_mode: mix_pos_3c
  #sign: -1
  #pos_offset: 0
  #pid :
    #position: [500.0 , 0.0 , 1.0]
    #mix_position: [3700.0, 0.0, 35.0]
    #impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## LL_A_P = 55
#HpESC_55:
  #control_mode: mix_pos_3c
  #sign: 1
  #pos_offset: 0
  #pid :
    #position: [500.0 , 0.0 , 2.0]
    #mix_position: [3700.0, 0.0, 30.0]
    #impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

## LL_A_R = 56
#HpESC_56:
  #control_mode: mix_pos_3c
  #sign: -1
  #pos_offset: 0
  #pid :
    #position: [80.0 , 0.0 , 4.0]
    #mix_position: [800.0, 0.0, 10.0]
    #impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    ##impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]


#############################
# RIGHT ARM
#############################

# RA_SH_1 = 11
HpESC_11:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_SH_2 = 12
HpESC_12:
  control_mode: idle
  sign: -1
  pos_offset: 0
  #pos_offset: -90 NOTE it was not working for the left_arm joint
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_SH_3 = 13
HpESC_13:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_EL_ = 14
HpESC_14:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_WR_1 = 15
LpESC_15:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_WR_2 = 16
LpESC_16:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_WR_3 = 17
LpESC_17:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]
    impedance:  [100.0, 20.0, 2.0, 0.01, 0.8]

# RA_HA = 19
LpESC_19:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

#############################
# LEFT ARM
#############################

# LA_SH_1 = 21
HpESC_21:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_SH_2 = 22
HpESC_22:
  control_mode: idle
  sign: -1
  pos_offset : 0
  #pos_offset: 90 NOTE it was not working for the left_arm joint
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_SH_3 = 23
HpESC_23:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_EL = 24
HpESC_24:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_WR_1 = 25
LpESC_25:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_2 = 26
LpESC_26:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_3 = 27
LpESC_27:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_HA = 29
LpESC_29:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]

#############################
# WAIST
#############################

# WST_Y = 31
HpESC_31:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 10.0]

# WST_P = 32
HpESC_32:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [3000.0, 0.0, 30.0]

# WST_R = 33
HpESC_33:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 10.0]
