# WALKMAN-ROS config

XBotInterface:
  urdf_path: "configs/ADVR_shared/bigman/urdf/bigman.urdf"
  srdf_path: "configs/ADVR_shared/bigman/srdf/bigman.srdf"
  joint_map_path: "configs/ADVR_shared/bigman/joint_map/bigman_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"
  
ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "CommandArray"
  jointstate_message_type: "JointState"
  ft_topic_names: ["/bigman/sensor/ft_sensor/LAnkle", "/bigman/sensor/ft_sensor/RAnkle"]
  imu_topic_names: ["/bigman/sensor/IMU"]

CommandArray:
  subclass_name: "CommandArrayMessage"
  path_to_shared_lib: "libCommandArrayMessage.so"
  subclass_factory_name: "commandarray_control_message"
  command_topic_name: "/bigman/group_position_torque_controller/command"
  joint_list_param_name: "/bigman/group_position_torque_controller/joints"

CustomCmnd:
  subclass_name: "CustomCmndMessage"
  path_to_shared_lib: "libCustomCmndMessage.so"
  subclass_factory_name: "customcmnd_control_message"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/centauro/position_controller/command"
  
JointState:
  subclass_name: "JointStateMessage"
  path_to_shared_lib: "libJointStateMessage.so"
  subclass_factory_name: "jointstate_jointstate_message"
  joint_state_topic_name: "/bigman/joint_states"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
