# CENTAURO config
XBotInterface:
  urdf_path: "configs/ADVR_shared/centauro/urdf/centauro_upperbody.urdf"
  srdf_path: "configs/ADVR_shared/centauro/srdf/centauro_upperbody.srdf"
  joint_map_path: "configs/ADVR_shared/centauro/joint_map/centauro_test_joint_map_upperbody.yaml"

RobotInterface:
  framework_name: "XBotRT"
  
ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "CustomCmnd"
  jointstate_message_type: "JointState"
  ft_topic_names: ["/ft_foot_1", "/ft_foot_2", "/ft_foot_3", "/ft_foot_4"]
  imu_topic_names: []#["/imu_1_data", "/imu_2_data"]
  
RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"
  
XBotRTPlugins:
  plugins: ["IkExample"]
  
CustomCmnd:
  subclass_name: "CustomCmndMessage"
  path_to_shared_lib: "libCustomCmndMessage.so"
  subclass_factory_name: "customcmnd_control_message"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/centauro/position_controller/command"
  
JointState:
  subclass_name: "JointStateMessage"
  path_to_shared_lib: "libJointStateMessage.so"
  subclass_factory_name: "jointstate_jointstate_message"
  joint_state_topic_name: "/centauro/joint_states"

  
RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
