# COMAN config

XBotInterface:
  urdf_path: "configs/ADVR_shared/coman/urdf/coman.urdf"
  srdf_path: "configs/ADVR_shared/coman/srdf/coman.srdf"
  joint_map_path: "configs/ADVR_shared/coman/joint_map/coman_joint_map.yaml"
  
HALInterface:
  lib_file: "libXBotEthernet"
  lib_name: "XBotEthernet"
  
RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "AdvrCommandMessage"
  jointstate_message_type: "AdvrJointStateMessage"
  ft_topic_names: []
  imu_topic_names: []

RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"

XBotRTPlugins:
  plugins: ["Homing"]
  #plugins: []
  io_plugins: []
  
NRTPlugins:
  plugins: []

MasterCommunicationInterface:
  framework_name: "ROS"
  
CustomCmnd:
  subclass_name: "CustomCmndMessage"
  path_to_shared_lib: "libCustomCmndMessage.so"
  subclass_factory_name: "customcmnd_control_message"
  joint_service_name: "/coman/position_controller/get_joint_names"
  command_topic_name: "/coman/position_controller/command"

JointState:
  subclass_name: "JointStateMessage"
  path_to_shared_lib: "libJointStateMessage.so"
  subclass_factory_name: "jointstate_jointstate_message"
  joint_state_topic_name: "/coman/joint_states"

AdvrCommandMessage:
  subclass_name: "CommandAdvr"
  path_to_shared_lib: "libAdvrCommandMessage.so"
  subclass_factory_name: "advrcommandmessage_control_message"
  joint_service_name: "/coman/position_controller/get_joint_names"
  command_topic_name: "/xbotcore/coman/command"

AdvrJointStateMessage:
  subclass_name: "AdvrJointState"
  path_to_shared_lib: "libAdvrJointStateMessage.so"
  subclass_factory_name: "advrjointstate_jointstate_message"
  joint_state_topic_name: "/xbotcore/coman/joint_states"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"

board_ctrl:
  eth_iface: pippo # does not taken into account -> rteth0
  boards_num: 35 #27 # 23 mcs + 2 fts

# assume boards of same type have the same policy bc_rate !!! 

mc_board:
  bc_rate: 2 # NOTE 2 is 1 kHz

ft_board:
  bc_rate: 2 # NOTE 2 is 1 kHz
  calibrate_offset: true

